### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by vkee** [ethz-asl/3d_laser_slam#1]
Any idea when this will be released? Eager to try this out!

**Comment by rdube** [comment]
Hi @vkee , thank you for your interest! laser_slam has already be released under a different repository: https://github.com/ethz-asl/laser_slam

You can find installation and demonstration instructions in our _SegMatch_ repository: https://github.com/ethz-asl/segmatch

I hope this helps!

**Comment by vkee** [comment]
Ah okay. Thanks a lot, it looks like some great work. I'm going to try it on autonomous vehicle domains.

**Comment by rdube** [comment]
Great! Let us know how it goes!
